name: Agente Cripto Automatico

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ejecutar-agente:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerias
        run: |
          pip install requests google-genai

      - name: Ejecutar Agente
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_ORIGEN: ${{ secrets.EMAIL_ORIGEN }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
        run: python main.py
