name: Agente Cripto Automatico

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ejecutar-agente:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerias
        run: |
          python -m pip install --upgrade pip
          pip install google-genai requests pandas

      # Se ejecuta de forma automática cada hora (Cron)
      - name: Ejecutar Agente en Vivo
        if: github.event_name == 'schedule'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_ORIGEN: ${{ secrets.EMAIL_ORIGEN }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
        run: python main.py

      # Se ejecuta ÚNICAMENTE cuando le das al botón "Run workflow" manualmente
      - name: Ejecutar Backtesting (100 Trades)
        if: github.event_name == 'workflow_dispatch'
        run: python backtest.py

      - name: Guardar Historial, Dashboard y Seguimiento
        if: github.event_name == 'schedule'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add posiciones.json historial.json candidatas.json
          git commit -m "Actualizar datos del dashboard y seguimiento [skip ci]" || exit 0
          git push
